### ISSUE TITLE
Could you make this into a Bot?

### ISSUE THREAD

**Issue by Setcon** [murjax/Discord-Distance-Calculator#1]
Good day,

Could you make this into an actual bot that could be added via link?

Or could you assist me with the missing parts? For example "use your own configuration for geocoder"

I don't know what to regarding this. Also I don't know what else is missing.

Kind Regards,
Setcon!

**Comment by murjax** [comment]
Yeah I should be able to do that. FYI the Geocoder is a wrapper for the Google Maps API. You won't need to configure anything if you're using a bot though. Let me see about creating one.

**Comment by Setcon** [comment]
Thanks!

**Comment by murjax** [comment]
[The bot has been posted.](https://discordbots.org/bot/186331510591193088) Let me know if you encounter any issues with it, as I literally just put it on a server this evening. As of this posting the bot is pending approval on Discord but as long as there's no issues with the server it should be approved shortly.

**Comment by Setcon** [comment]
Awesome! Thanks man!

**Comment by Setcon** [comment]
Hey, I have been trying every hour since you replied. I keep getting 
"Sorry we tried very hard but something went wrong :(

Forbidden

403"

Is the bot waiting approval from the discord guys?

And thanks again for the effort

**Comment by murjax** [comment]
It appears as though the server closed. I restarted it and will keep an eye on it. This might happen again and in which case I'll write a script sometime this week to restart the server when it goes down. Thanks for letting me know!

**Comment by Setcon** [comment]
Thanks! 

Though I still have the same issue at the moment :)

**Comment by Setcon** [comment]
Hey man,

Still getting the same issue.

Thanks :)

**Comment by murjax** [comment]
It's going to take me another week, but I haven't forgotten about you. In fact I just spent the past couple days cleaning up some code to fix the issue. I'll keep you posted.

**Comment by Setcon** [comment]
Thanks! :D Im pretty sure once your bot is running I wont be the only one using it.

**Comment by Setcon** [comment]
Sad panda here :(

Though still a hopeful panda

**Comment by murjax** [comment]
[Can you try this now?](https://discordbots.org/bot/186331510591193088) The server has been up for 24 hours with no issues. It should be good now.

**Comment by Setcon** [comment]
Could you maybe make it post km and miles?

My community works mostly on metric.

And thank you so much! 

I will add a calculator for them anyways to convert

**Comment by murjax** [comment]
By default the bot responds in miles, but you can get kilometers by adding `km` to your message. (e.g. `!distance Paris,France Florence,Italy km`)

**Comment by Setcon** [comment]
Oh awesome! 

Thank you very much once again!

**Comment by murjax** [comment]
Assuming everything is set here. Let me know if you have any further issues or questions. Closing the issue.
